### ISSUE TITLE
[Irritation] Brews for beans that are set to "consumed" disappear from the "last brews" list on the home screen

### ISSUE THREAD

**Issue by benedetto** [graphefruit/Beanconqueror#176]
I marked this with [irritation] since I'm not sure if it is intended behaviour, if just I find it a bit counterintuitive or if it was not intended:

### Observed behaviour
In the "Brews" screen, once I mark a bean sort as "consumed", the brews of this bean are shifted to the "Archived" tab, which I can understand, since those brews are currently not relevant any more. However, those brews also disappear from the "Last Brews" list on the home screen of the app.

### Expected behaviour
On the home screen I would expect the archived brews to persist, since they are still my last brews nonetheless and some kind of "recent brew history", even if the been is used up now.

As written above, I'm not sure whether this is just my personal view on this. I don't know whether other people see that all different or if it was something nobody thought about so far and it just happened to be as it is now...

**Comment by graphefruit** [comment]
Hi @benedetto,
first of all: Thanks for your detailed feedback in each issue, I really appreciate this!
In a nutshell: This behaviour is intended, in the actual described way.

When is a brew archived?
When a bean, a mill or a preparation method is archived and the brew is related with this.

Why are archived-brews not displayed on the home page?
The brews give the possibility to be repeated.
When you repeat a brew, you can not use archived beans, mills or preparation methods.

So when you repeat and the parameters would be preset, the parameter for one of the three above would be changed. 
-> This could lead to a confusion for the user. (When you're inside the Archive-Tab and repeat, you should know that the parameters will be changed)

I've just heard from 2 people about this irritation, but this could be because of multiple reasons
- Homescreen is not used in the way its intended for them
- The Homescreen is always skipped directly to the brews
- etc.

One possible solution could be to label the archived brews at the dashboard page, or the label will be changed to "Last not archived brews or last active brews"?

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/110166508-c5441e00-7df4-11eb-9b41-3fa81ae03b3f.png)
Ok I've thought about this now, I've added the archived in the list, but changed the "..." to the archive icon, which will not give the possibility to edit or repeat the brew, this would be need to be done in the normal brew tab.

I think this will be a good tradeoff

**Comment by benedetto** [comment]
Hi @graphefruit, that looks really great. Thanks also for the always quick reaction and appreciation.
