### ISSUE TITLE
Feature request: Add photos to brews

### ISSUE THREAD

**Issue by tokenstar** [graphefruit/Beanconqueror#190]
Because latte art

**Comment by graphefruit** [comment]
Hello @tokenstar,
you can already add photos to brews.
You need to activate this via menu -> brewing parameters -> manage parameters -> after brewing -> attachments.

Does this resolve your request?

**Comment by tokenstar** [comment]
Thanks! 2 followups 

"attachments" is unclear, suggest renaming "Photos"?

Would be awesome if for photos there was a simple crop/rotate editor as cups and bean bags are not the same aspect ratio as camera.

**Comment by graphefruit** [comment]
You are right, actually attachments just support photos.
It was intended to support more than just photos. 
I think a solution could be "attachments/photos" I'll do some thoughts about this.

Secondly regarding the crop feature: I see the need, but there would be a (half) workaround yet.
Using the camera normally and then add the photo afterwards.

For the crop/rotate editor I'd like to make another story because its a complete different request here and I'd like to not combine both here.

**Comment by graphefruit** [comment]
Was renamed, and is fixed in the next version
