### ISSUE TITLE
Support QR-Code

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#219]

**Comment by dulitz** [comment]
Is this documented somewhere?

The strategy that I think would be most compatible with roasters' branding, given that they probably want to include only one QR code max is that the QR code encodes a URL, and at that URL is a standard HTML page with structured bean data in HTML microdata/RDFa/OpenGraph format.

Beanconqueror would fetch the page and parse the structure. The next step in the user flow, after scanning the QR code, would be to show the bean inventory page with certain values pre-populated and other values being explicitly prompted for.

This would be robust -- if the roaster has a QR code but no specific Beanconqueror support, the page likely has OpenGraph information about the roaster itself (which can be prefilled). If they add support for bean-specific microdata that Beanconqueror can parse, that data can be loaded/parsed by any app.

The incentives are good: if the bag has a QR code, I as a Beanconqueror user will have an incentive to scan it because it'll probably save me some typing (and maybe a lot). Roasters have an incentive to populate the page with as much specific data as is practical but no more (if it's too hard for them to update a webpage for each new version of a roast they don't have to). And other bean apps have an incentive to use (and encourage the user of) the same webpage format.

**Comment by graphefruit** [comment]
Hello @dulitz,

it will be documented in the near future.
The solution will come as following:

A roaster can create a QR-Code via a specific Beanconqueror website, with specific data (images, roasting date, weight, bean origin data, etc.)
This QR-Code will inherit a link which points out to the https://beanconqueror.com website.

Scan via QR-Code-App:
Like on other apps the webpage will ask the user to open the link inside Beanconqueror ->  The bean will be added.

Scan via Beanconqueror directly:
The Bean will be added directly.

**Comment by graphefruit** [comment]
Edit:
The Link will inherit a unique qr-code id (e.g. beanconqueror.com/qrcodeid=123456789), where the app will ask then the beanconqueror-server to give all the needed information to load.

**Comment by graphefruit** [comment]
First version will be available in 6.1.
Going to close this one.
