### ISSUE TITLE
Enhancement: Automatic backup

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#284]
If a user didn't start the app every day, the backup routine will have an issue, if you start the app after a month, because all backups will be deleted directly.

**Comment by hermanmak** [comment]
I think based we can inspire based on how 1Password local vaults work.
https://1password.community/discussion/125034/local-vault#:~:text=1Password%20always%20works%20from%20a,event%20that%20we%20are%20offline).

(1)When user opens app, and is connected to wifi, and has Dropbox sync enabled
We take current local db and merge with Dropbox.

User can stay offline or not be connected to wifi..it will just work on local db, each time user opens app we reevaluate if we can perform (1)

**Comment by graphefruit** [comment]
@Gandalf-the-Blue 
Beanconqueror does automatic backups.
On iOS -> Files -> on my Phone -> Beanconqueror ->  auto_xxx.zip
on Android -> Android_Data/com.beanconqueror.com/Downloads/auto_xx.zip

After Android removed the permissions to backup to the Download folder, there needed to be a new work arround.

The backups are a Father, Child system, for seven days.
Hope that helps.
Best
Lars

**Comment by graphefruit** [comment]
> So, on Android, there are currently no automatic backups, am I understanding that right?
> Is there a solution in mind/being implemented to get around this Android issue?

Android is doing an auto backup aswell.
you'll find this below: /Android_Data/com.beanconqueror.com/**/*.zip

**Comment by graphefruit** [comment]
> I can't find the Android_Data folder. Are you referring to Android/data ?
> 
> But there too, no such folder exists. I can only find 1 empty folder in Android/media/com.beanconqueror.app/

Have a look here:
/storage/emulated/0/Android/data/com.beanconqueror.app/files/Download/Beanconqueror_export/Beanconqueror_automatic_export*.zip
(Or ///datacom.beanconqueror.app/files/Download/Beanconqueror_export)

**Comment by graphefruit** [comment]
> Nope, neither of those folders exist/can be accessed.

Maybe use another file-system Manager like Totalcommander.
What Android Version do you have, which phone, custom ROM?

**Comment by graphefruit** [comment]
@Gandalf-the-Blue did you try to access with ADB?

**Comment by graphefruit** [comment]
Never heard of GrapheneOS, and I can't tell how they behave.
Ateleast with ADB you could try to access it.

**Comment by graphefruit** [comment]
@Gandalf-the-Blue 
I've written an tutorial for Android to transfer with ADB: https://beanconqueror.gitbook.io/beanconqueror/how-to/backup-and-import-android-14 
Happy to get any feedback on this.

**Comment by graphefruit** [comment]
After there hasn't been any more discussion on this topic, this ticket will be closed now.

**Comment by RagingCactus** [comment]
I have recently moved Android phones and found the current workflow using `adb` (while it did work) very inconvenient. I doubt that most non-expert users are able to make this work as expected.

I know this would probably be a little additional, but I believe the cleanest solution would be to let the user pick a backup location themselves. My understanding is that this can be done by using the Android Storage Access Framework (SAF), although I am not an Android developer. This would also have the added benefit that users can choose cloud storage providers or sync apps that also use SAF to get folder access. The end result would be that users can automatically backup/sync the Beanconqueror backup files to their backup storage.

This could also be used to simplify the restore process: Simply pick a backup file to restore using SAF and restore from it.

**Comment by graphefruit** [comment]
Hello @RagingCactus,
thank you for your feedback here.
Its easy to make a switch, if you don't need to have images or graphs, then you just can export / import, everything else is more hard.

After Google has restricted the possibility to write to the /Download/ folder anymore, its much more complicated now.

The backup storage would need to inherit all data aswell, graphs, images, and the .ZIP file to import.

I'd be more then happy to receive a pull-request to speak to the referenced SAF or any other possibility to sync to another backup storage.

Have a great cup of coffee
Lars

**Comment by RagingCactus** [comment]
First of all, thanks for taking the time to respond, I appreciate your work with this app a lot!

While I'm not an Android developer, I would maybe try adding this if this was a native application. But sadly I don't believe that I have the time to learn Cordova/Android to tackle this in the near future.

However, I will leave some notes and what my research has shown should be the solution:

It is correct that you cannot just open arbitrary directories in modern Android. You can, however, specifically request access to a specific directory from a user. Lots of other apps use this, for example the messenger app Signal (for picking a backup location) or even the camera app OpenCamera (see https://sourceforge.net/p/opencamera/code/ci/a6673ade58550ed468d53a430608fecfe6bcd721/tree/app/src/main/java/net/sourceforge/opencamera/MainActivity.java#l4656 and https://sourceforge.net/p/opencamera/code/ci/a6673ade58550ed468d53a430608fecfe6bcd721/tree/app/src/main/java/net/sourceforge/opencamera/MainActivity.java#l4730 for key parts of the implementation) use this.

From what I've gathered, Beanconqueror would need to use an `ACTION_OPEN_DOCUMENT_TREE` intent to have the user pick a directory to access (see https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory). This can be almost any directory aside from some very specific restrictions (see https://developer.android.com/training/data-storage/shared/documents-files#document-tree-access-restrictions). After that, the app can now access the selected directory using the URI that comes back from the intent. This access, by default, lasts until the device is restarted.

However, the app can also persist the permissions by using the `takePersistableUriPermission` method, see https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions.

I'll also copy-paste the code samples from the documentation I have referenced above for convenience:
```java
public void openDirectory(Uri uriToLoad) {
    // Choose a directory using the system's file picker.
    Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);

    // Optionally, specify a URI for the directory that should be opened in
    // the system file picker when it loads.
    intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, uriToLoad);

    startActivityForResult(intent, BEANCONQ_BACKUP_DIR_REQUEST);
}

@Override
public void onActivityResult(int requestCode, int resultCode,
        Intent resultData) {
    if (requestCode == BEANCONQ_BACKUP_DIR_REQUEST
            && resultCode == Activity.RESULT_OK) {
        // The result data contains a URI for the document or directory that
        // the user selected.
        Uri uri = null;
        if (resultData != null) {
            uri = resultData.getData();
            // Perform operations on the document using its URI.
            // Persistent permission code copy-pasted below:
            final int takeFlags = intent.getFlags()
                            & (Intent.FLAG_GRANT_READ_URI_PERMISSION
                             | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
            // Check for the freshest data.
            getContentResolver().takePersistableUriPermission(uri, takeFlags);
        }
    }
}
```

From what I've gathered you would need appropriate Cordova plugins to handle this in an Ionic app. In my (very brief) research, I haven't found a suitable plugin, but that could simply be because I have almost no understanding of Cordova. If no plugin exists, I believe creating one shouldn't be _too_ hard, as the required native Android code looks very simple: Just fire off an intent, handle the result, and try to take the persistent permissions.

I'm sure every Android user would love if someone would be able to implement this.

**Comment by graphefruit** [comment]
> First of all, thanks for taking the time to respond, I appreciate your work with this app a lot!

Thank you :)

> While I'm not an Android developer, I would maybe try adding this if this was a native application. But sadly I don't believe that I have the time to learn Cordova/Android to tackle this in the near future.
Even so I'm developing the app, I'm not a Android developer aswell.
Cordova spawns a "website" and on this I'm developing with Angular.
Cordova also have the bridge then to talk via JavaScript to the cordova-plugins which are then in Android or iOS code.

In the end, when we think about a solution of backing up data, it would be a good solution to have it both for Android and for iOS (even so on iOS its much more easy actually), maybe even with a DropBox sync or something like this.
Because then we come into the second category: People want to connect different phones and sync data aswell, and not just backing up.

> From what I've gathered you would need appropriate Cordova plugins to handle this in an Ionic app. In my (very brief) research, I haven't found a suitable plugin, but that could simply be because I have almost no understanding of Cordova. If no plugin exists, I believe creating one shouldn't be _too_ hard, as the required native Android code looks very simple: Just fire off an intent, handle the result, and try to take the persistent permissions.

Back in the times, I've searched, but the only plugin I've found it was possible to sync JSON-Data, but just for a smaller amount. JSON-Data bigger some MB's got lost, or corrupted, which doesn't help in the end.

> I'm sure every Android user would love if someone would be able to implement this.

I hope that someone has the skills joining and getting in touch to discuss a concept and writing the code, for me its to far away to do the implementation on my own.


Have a great cup of coffee
Lars

**Comment by RagingCactus** [comment]
While it's not automatic, #806 at least directory-based import/export of all files (including attachments, images, flow profiles and so on) back to Android.
