### ISSUE TITLE
[Request] Desktop Builds?

### ISSUE THREAD

**Issue by mots** [graphefruit/Beanconqueror#295]
Hi - seeing how this is made with ionic, it should be doable to have desktop electron builds, right? I'd love to have a Linux version available!

**Comment by graphefruit** [comment]
Hi @mots,
actually I'm not planning to release a desktop build.
Ionic Supports a Progressive Web App (PWA).

But features like Bluetooth or Camera etc. would not be working and needed some new code.

I don't know what would be the main usage in the end.

Also without any sync (with a login user) dataloss would be a big problem

**Comment by graphefruit** [comment]
Maybe some short update:
Adding the PWA wouldn't be a big deal.
All features like adding beans or brews would be possible.

But the main features like smartscale, adding of images, or the latest feature i'd like to do: QR-Code integration would not work at all.

Also after I'M storing most of the data in an indexdb - if someone would close the browser and have a cleanup system running, all added data would be deleted.

Maybe you can give me some more insights

**Comment by peschee** [comment]
> Also after I'M storing most of the data in an indexdb - if someone would close the browser and have a cleanup system running, all added data would be deleted.

I think it should be technically possible to use and persist the db. See the IndexedDB API docs https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API and the "See Also" section. There are libraries that a) abstract the API and b) can add persistence.

It this something you'd be willing to pursue? I think a PWA (and hence a Desktop-Version) would be spectacular, especially for those who do not need the OS integration for device support such as smart scales etc.

**Comment by graphefruit** [comment]
> > Also after I'M storing most of the data in an indexdb - if someone would close the browser and have a cleanup system running, all added data would be deleted.
> 
> I think it should be technically possible to use and persist the db. See the IndexedDB API docs https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API and the "See Also" section. There are libraries that a) abstract the API and b) can add persistence.
> 
> It this something you'd be willing to pursue? I think a PWA (and hence a Desktop-Version) would be spectacular, especially for those who do not need the OS integration for device support such as smart scales etc.

One solution would be to use a PouchDB connector, which is using CouchDB in behind
But those services are not for free.
So without having costs covered, I see no possibility for this.

The preferred solution on my side would be a user login where data are stored on the servers, because there is a lot more possibility given than just an online sync.
But also here, without having a cost covering solution, this will get quick costly.
Actual 0% of my yearly costs are covered - and I'm not talking about my programming time.

The simplest solution, I've already written above: Putting a PWA online via Github pages, but if the OS clears this one, users will have a rough/bad time if they need to start over, and in the worst case, they have a bad mindest then against Beanconqueror - even when putting notice signs before.
And also I'd need to optimize the PWA to accept e.g. tabindex to navigate via keyboard, and also some functions are not working like date-time choosing because I needed to use another native plugin.

So without a sponsor ship, and also without clarify the privacy this will not be taken further into account - sorry!
Have a great start into the weekend
Lars

**Comment by gudvinr** [comment]
IMO, web version by itself is pretty much useless but something like self-hosted server with web app that uses server as backend will be a banger.  
That will solve synchronization issues between different instances but far more involved than just compiling PWA for desktop.

Good examples of this approach are [wger](https://github.com/wger-project/wger) (workout manager) and [tandoor](https://github.com/TandoorRecipes/recipes) (recipes manager).

**Comment by graphefruit** [comment]
This Ticket has been idle for long, I'll close it now
