### ISSUE TITLE
Graph enhancements

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#359]
The weight/flow graph has changed in version 6 and in my opinion, a few things have changed to be not as nice as they were before:

* the flow is now fixed to 10ml/s, the weight is fixed at 100ml - both are too much for espresso. I can barely see the weight change :(
* The graph now starts on the right side and slides to the left
* only a window of 30s is visible
* in the (very very nice!) landscape view, the x-axis ticks are not shown (at least for me... I'm using a Samsung S9 with Android 10)

Portrait:
![image](https://user-images.githubusercontent.com/431045/167251845-34d615f1-dc07-4e4b-b76b-ceb8539c1e41.png)

Landscape:
![image](https://user-images.githubusercontent.com/431045/167251874-9249aa72-9779-40df-bb25-3968c3ffd436.png)

My enhancements for the graph would be:
* Start on the left at 0.0s. Generally the start right, slide left is OK but personally I like it more if the graph starts on the left side and advances over the graph area
* maybe show a window of 45s or more or start compressing the x-axis instead of using a window
  * a more sophisticated version could be to show the last 20s or so and compress the rest into a smaller area 
* bring back auto scale for weight and flow, and maybe start at "reasonable" limits depending on the preparation type (e.g. 0..2ml/s + 0..50ml for espresso; 0..10ml/s + 0..250ml for v60)
  * Interestingly, if you open up the brew later, the graph looks really nice!
* better distinguish the primary and secondary y-axis, for example by showing the units or the colors directly over the axis ticks

Yet another nice touch would be vertical lines indicating the times for pre-infusion/blooming end and first drop.

But these are just some ideas, maybe someone can come up with even a better idea :)

**Comment by graphefruit** [comment]
Good Morning @reox,
sorry for the late reply.
The new graph was added, because the old one was jumpy, and on a longer brew time realy nested and hard to read.

Start from the left:
For streaming left to right i've made an ticket here: https://github.com/nagix/chartjs-plugin-streaming/issues/162

Compression or something like this is not that supported with this plugin.
If you find any other plugins which may be handle this solution better, and is performant and not junky, please let me know.
Maybe we can go up to 45s on the frame, I didn't try it out, its rather that the first lines will appear later, as far as I know, which would be to late for pressure profiling or something else.

Autoscale:
The Graph is autoscaling, but after I've set the first initial marks it doesn't look like.
I've made two different initials for espresso and filter, I gonna have a look at them and fit them better.

If you open the graph later one, the normal chartjs plugin is used, and not the streaming one.

Difference of primary and secondary y-axis:
Its possible to show the ticks over the line with tooltips but you'll come into the issue that every 10hz a new value is written, this would explode the chart.
I don't know if the different axis can be colored, would need to have a look.


Pre-Infuion/Blooming line:
Would be possible, but users would need to press the timing button manually, this won't be anything automatic calculated.

Landscape mode: 
I gonna have a look where the Axis's wents.

The graph changes for this version, where already where hard to integrate, so I'm happy for every helping hand here.

**Comment by reox** [comment]
> The graph changes for this version, where already where hard to integrate, so I'm happy for every helping hand here.

no worries, the new graph is already very nice - especially that you can see now the flow better! If there are technical limitations, you can not do much - that is clear.
Unfortunately, all I can do to help is to tell you my user experience 😅

**Comment by graphefruit** [comment]
Hey @reox,
I've made smaller fixes, specially defined the range for espresso, please have a look

**Comment by reox** [comment]
Yes that look already better from the ranges! But with the realtime flow, it looks even more cluttered IMHO 😅
Especially, if all lines are over each other like in this example:
![image](https://user-images.githubusercontent.com/431045/169645232-2d1937a3-2a57-42c1-9648-5789144b86ac.png)

**Comment by graphefruit** [comment]
In the next version there will be the possibility to hide the different graphs for filter/espresso modes so there should be less clutter
