### ISSUE TITLE
Predefined values for "Grind Setting" and "Brew Temperature"

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#496]
Normally I don't change "Grind Setting" and "Brew Temperature", so a predefined value would help.

**Comment by graphefruit** [comment]
Hey @LagaV,
this is already possible with all wanted parameters.
Please go to the menu-> brewing parameters -> Define default parameters.
On this menu you can choose the values which should be preset, when you start a new brew.

You can also customize this, down to the preparation method, and overwrite the global value.
With the next version you'll get a new button, to also directly select your preparation method you want to brew next, instead of taking the last one.
Also you get the possibilty with the next version, to choose your preset values for repeat (actually it will take all), and you can unselect all, and just select the values you realy want to repeat.

Hope that helps, else let me know.
Have a great evening
Lars
