### ISSUE TITLE
Scale recording lost, if scale is switched off before brew saved

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#508]
I‘m not sure if this is intended, but unfortunately the brew recording is not saved, if the scale is turned off before the brew is saved. As the data is available, I would expect, that for the brew record everything is saved, that is „in memory“.

**Comment by graphefruit** [comment]
This issue was reported via E-Mail and Discord aswell.
One thing to prevent the graph from beeing deleted: https://github.com/graphefruit/Beanconqueror/issues/491
The other thing is, that with a new beta-build the user couldn't reproduce the issue anymore, maybe because also of some changes I did with the graph library.

**Comment by LagaV** [comment]
Closing it, as already fixed.
