### ISSUE TITLE
After latest firmware update Microbalance throws an error on start

### ISSUE THREAD

**Issue by Cancercookie** [graphefruit/Beanconqueror#600]
Android

When in Beanconqueror the Microbalance seems to connect properly, but when I open a new brew I receive the error "No weight values?". If I start a brew the graph or time do not update.

I recently update the scale to the latest firmware version so maybe that is what is causing the issue.

**Comment by graphefruit** [comment]
Hey @Cancercookie,
thanks for opening up a ticket.
I've checked today.
I've got the Firmware 302 installed - and it works without issues.
Can you try to set the language of the DiFluid Cafè app to english and see if you can update?
Else please make sure to set the command delay to like 300ms in the settings in Beanconqueror and see if the issue is gone.

Thanks
Lars

**Comment by Cancercookie** [comment]
Setting 300ms as a delay seems to have solved the issue (was 50ms before). 
Thanks ❤️

**Comment by graphefruit** [comment]
You can play around and lower the ms.
You find all information here: https://discord.com/channels/994167114611044443/1144314675048218674
