### ISSUE TITLE
iOS - Database rollback / Data are missing

### ISSUE THREAD

**Issue by abaebae** [graphefruit/Beanconqueror#694]
Hi, I noticed today that the database for brews and beans had a rollback to today (added last shot yesterday) back to 01.04.2024. I checked the data export, but everything since 02.04.2024 is missing. Log files is attached.
[attachment.json](https://github.com/graphefruit/Beanconqueror/files/14967094/attachment.json)

**Comment by graphefruit** [comment]
Hey @abaebae,
I'm realy sorry for this.

I've linked this issue on the plugin I'm using: https://github.com/ionic-team/ionic-storage/issues/317

Also I'd ask you to join the Beanconqueror Discord, there has been a lot of discussion, after this issue is appearing "right now" on iOS sides.

The thread is following:
https://discord.com/channels/1095806336907874347/1227620801705021500

There will be more instructions/questions following

**Comment by graphefruit** [comment]
There has been a workaround added.
A popup will be displayed when a database access cant be established.
The rest is needed to be done at apple side.
