### ISSUE TITLE
DiFluid microbalance flow chart jagged

### ISSUE THREAD

**Issue by simons-plugins** [graphefruit/Beanconqueror#720]
As the screen shot the flow charts with my new DiFluid microbalance produce saw tooth profiles whereas I got smooth curves with the decent scale. 

![IMG_6459](https://github.com/graphefruit/Beanconqueror/assets/20978140/63e7a20c-d412-46f8-9f9f-f017605bd9f8)

[Beanconqueror_Flowprofile_JSON_08_17_28_01_06_2024.json](https://github.com/user-attachments/files/15520852/Beanconqueror_Flowprofile_JSON_08_17_28_01_06_2024.json)

**Comment by graphefruit** [comment]
Looks like an espresso brew.
May you can do a brew with the decent scale on the difluid and see how it behaves? 
Also please pass me the .xls file to the shot its easier to read then the .JSON.
How does the "smoothed" curve looks like?

**Comment by simons-plugins** [comment]
Do you mean stack the decent scale on the DiFluid ? Not sure how I record both plots though?

**Comment by simons-plugins** [comment]
This is the excel with smoothed, which is similar shape.  

[Beanconqueror_Flowprofile_Raw_14_20_58_04_06_2024.xlsx](https://github.com/user-attachments/files/15552011/Beanconqueror_Flowprofile_Raw_14_20_58_04_06_2024.xlsx)

**Comment by graphefruit** [comment]
> Do you mean stack the decent scale on the DiFluid ? Not sure how I record both plots though?

Two phones

**Comment by graphefruit** [comment]
> This is the excel with smoothed, which is similar shape.
> 
> [Beanconqueror_Flowprofile_Raw_14_20_58_04_06_2024.xlsx](https://github.com/user-attachments/files/15552011/Beanconqueror_Flowprofile_Raw_14_20_58_04_06_2024.xlsx)

Thanks for the file.
I had a look now.
It looks like something is completely wrong.
When looking at the data, it looks like that max 3-4 values are send by the scale, I have checked it with my DiFluid TI, the issue is mine sends 4 to 5 with not that high delays.
```
10:26:01.761 -> 10:26:02.042
```
Thats an offset of about 300ms for the next value.

My delays are about 200 - 250ms.

The big issue comes that the timestamp delay on the realtime flow is going up to like 20 000 to 30 000 on your side.
I had a look on a sample espresso brew on my side, my max timestamp delay is 900 and normaly 700, and that constant.

Sample from my timestamps:
```
719
720
738
721
721
701
720
718
721
720
720
720
720
720
720
719
720
725
722
720
716
954
959
964
959
720
716
749
723
722
691
717
719
719
721
720
720
719
721
721
728
721
719
711
717
721
```

Sample from your timestamps:
```
15319
15612
15919
16200
16519
16800
919
881
919
18000
18319
18600
18919
19199
19519
19799
921
895
920
21000
21319
21599
21919
22200
22519
22800
919
881
919
24000
24319
24600
24919
25200
25522
25800
930
877
919
26999
27320
27600
27919
28215
28519
28799
912
881
920
30000
30319
30599
30919
31199
31519
31799
920
880
920
33000
33319
33600
33919
34199
34518
34799
880
881
880
36000
36279
36599
36880
37200
37479
37800
879
921
879
39000
39279
39599
39884
40200
40482
40800
879
```

Please make sure to:
1. Deactivate the vibration filter for the DiFluid
2. Update the firmware to the latest if possible
3. Remove all bluetooth-devices connected to your phone
4. Check that no battery-saver is active
5. Check your phone has a minimum of 80% Battery power when testing
6. Even test it with some other phones, maybe this helps

Because of the mentioned things above, the calculcation struggles and therefore the graphs are looking realy strange.

**Comment by graphefruit** [comment]
Hey @simons-plugins,
Did the issue resolve?

**Comment by simons-plugins** [comment]
> Hey @simons-plugins,
> 
> Did the issue resolve?

Sorry been trying to test and raised to DiFluid. 
I had one chart that was smooth, ie it must have reported more frequently. I have tried lots of settings and can't make it repeat. 
It also is not auto timing off after the 2 minutes setting (staying on for over an hour so battery dies in days) and suffering from weight drift so I'm going to return if I can.

**Comment by simons-plugins** [comment]
It's low flow setting. That needs to be turned on. That bit is working as expected now. 
The fact the weight drifts and it doesn't turn off are bigger issues, although nothing to do here.
