### ISSUE TITLE
Ground coffee default value not applied

### ISSUE THREAD

**Issue by Chais** [graphefruit/Beanconqueror#728]
I have set ground coffee to default to the amount of beans.  
![Screenshot_20240618-095006_Trebuchet.png](https://github.com/graphefruit/Beanconqueror/assets/1783098/765c00f6-2511-4d77-ae67-e2cfeb1ab09f)

But when I change the amount of beans the amount of ground coffee is not updated accordingly.  
![Screenshot_20240618-081131_Trebuchet.png](https://github.com/graphefruit/Beanconqueror/assets/1783098/ee8ffc8d-0e00-4d3f-be54-83e75f55815a)

**Comment by graphefruit** [comment]
Hello @Chais,
thanks for the ticket.
Beanconqueror does not apply any logic between Bean Weight & Ground Coffee.
The intention when adding the Bean Weight parameter, was that people wanted to track retention.
I'm not planning yet to update the Bean weight accordingly to the used ground coffee, when this value is higher then the actual bean weight. 
Because it could be also the last retention in the mill that you put 19 in and got 20 out e.g.

**Comment by Chais** [comment]
I have misunderstood the text then. Thanks.

**Comment by graphefruit** [comment]
So i going to close this ticket now
