### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by jjsil** [graphefruit/Beanconqueror#730]
Hi @graphefruit!

In the process of setting up a local dev environment to try some changes to the app, I tried to run the tests but run into some compile-time failures when running `npm test`. They are mostly about trying to import `IonicStorageModule` from `@ionic/storage` (maybe left-over from a migration to `@ionic/storage-angular` in ionic 7?).

I managed to fix those in my local environment but then run into a lot of test failures, mostly having to do with resolving dependencies. I've fixed a few of those locally as well, but before I go further or send some PRs to fix these failures, I wanted to check if I'm maybe trying to run these wrong? Are there specific steps I should follow to run the tests?

In case I'm not doing this wrong, would fixing the tests be of interest? Or is this not something you are using? If it would be useful, I could spend a bit more time trying to get them running and passing.

Cheers,
Juan

**Comment by graphefruit** [comment]
Hey @jjsil,
thanks for getting in touch with me here!
I really appreciate every helping hand here! 

Regarding the test:
TBQH: I didn't invest any time in it and I'd be more then happy for structures, helps, advices etc.

The structure is growing since 7 years, and I mainly do the most all of my own.

I know that @AdrisGithub did a branch for this and did many things already here, maybe you can takle this one from there? 
Also we got a PR here pending:
https://github.com/graphefruit/Beanconqueror/pull/683

Aswell as the branch: https://github.com/graphefruit/Beanconqueror/tree/bugfix/working-tests

I'm also active on Discord, and Beanconqueror got an own discord, maybe the discussion / chats would be easier for the follow up then here - But thats up to you.

Have a great cup of coffee & Happy to hear back from you
Lars
