### ISSUE TITLE
Importing backup without images leads to issues

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#833]
The first beta tests showed, that when you import a backup and images are missing with this, and you add images later on, it takes the wrong image-number because its not in the file-system, but already set in the .JSON-Data.

**Comment by RagingCactus** [comment]
>[!IMPORTANT]
> **This issue is also present in the old Cordova 7.5.0 version.**
# Reproduction Steps

* Import `Beanconconqueror.zip` file that includes beans and methods that have images attached
  * This will not import any images on Android (unless importing from the special `/sdcard/Android/data/com.beanconqueror.app/` directory) as the app does not have access to images in the same directory as the import file, even if they are present
  * Regardless of the reason, the bug is reproducible when the image files themselves are not imported
* Add new images. It does not matter if they are added to already existing data or new data.

# Root cause

When importing just the JSON file, the file names of attachments (for example `beanconqueror_image4.jpg`) are preserved. However, the actual image files are not imported as they are not accessible or missing.

When new images are now added, they start with the file name `beanconqueror_image.jpg` and continue with `beanconqueror_image1.jpg` and so on. Once `beanconqueror_image4.jpg` is reached there will be multiple references to that file: 

1. The old entries from the data import.
2. The new entry where the image was just attached to.

It now looks like the new image was "copied" to old entries.

# Solution
I will try to use UUIDs for attachment file names to prevent collisions with past names.

Incidentally, this should also allow us to remove the cache buster in `UIFileHelper.getInternalFileSrc` to allow for better caching.
